# https://wandb.ai

wandb:
#  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  _target_: src.utilities.wandb_callbacks.MyWandbLogger
  entity: "abg"  # Set to your wandb username
  name: null   # will be automatically set to the name of the run (plus timestamp, etc.)
  tags: []
  notes: "..."
  project: "Spherical-DYffusion"  # Match the project name from your URL
  group: ""
  resume: "allow"          # Allow resuming if needed, or create new run
  reinit: False            # Changed from True to False to avoid deprecation warnings
  mode: "online"            # Changed from "disabled" to "online" to enable wandb logging
  save_dir: ${work_dir}/
  offline: False           # set True to store all logs only locally
  id: null                 # pass correct id to resume experiment!
  resume_run_id: null      # Use this to resume a specific run using a NEW run ID
  log_model: False         # True or 'all'
  prefix: ""
  save_to_wandb: False      # Disable saving artifacts to avoid sync issues
  save_to_s3_bucket: False
  save_last_ckpt: False     # Disable checkpoint upload to avoid sync issues
  save_best_ckpt: False     # Disable checkpoint upload to avoid sync issues
  log_code: False           # Disable code logging to avoid sync issues
  settings:
    _save_requirements: False
    _disable_stats: True
    _disable_meta: True

