# SOMA MSE + Cosine Direction Loss  
_target_: src.losses.soma_losses.make_soma_composite_loss
base_loss_name: "mse"
enable_direction_loss: true
direction_weight: 0.1
direction_loss_config:
  zonal_var: "timeDaily_avg_velocityZonal"          # Name of zonal velocity variable
  meridional_var: "timeDaily_avg_velocityMeridional"     # Name of meridional velocity variable  
  loss_type: "cosine"
denormalize_primary: false
denormalize_direction: false
# datamodule will be set automatically by experiment
