defaults:
  - _base_model_config.yaml
  - _self_

_target_: src.models.fno_time.fnonet3d.FourierNeuralOperatorNet3D
embed_dim: 64
num_layers: 4
num_fno_modes: 16
padding: 8
padding_type: "constant"
activation_function: "gelu"
normalization_layer: "instance_norm"
dropout: 0.0
big_skip: true
use_mlp: false
mlp_ratio: 2.0
pos_embed: false
in_chans: 12 #(window + 1) * channels, with window=1: (1+1)*6=12
# out_chans will be set dynamically

# Use SOMA denormalizing loss for physically meaningful training
loss_function:
  _target_: src.losses.soma_losses.SOMADenormalizingLoss
  base_loss_fn:
    _target_: torch.nn.MSELoss
    reduction: mean
