# Example configuration for SOMA direction loss

# Simple configuration - just primary loss with denormalization
loss_function_simple:
  _target_: src.losses.soma_losses.make_soma_composite_loss
  base_loss_name: "mse"
  enable_direction_loss: false
  denormalize_primary: true

# With direction loss enabled
loss_function_with_direction:
  _target_: src.losses.soma_losses.make_soma_composite_loss
  base_loss_name: "mse"
  enable_direction_loss: true
  direction_weight: 0.1
  direction_loss_config:
    zonal_var: "timeDaily_avg_velocityZonal"          # Name of zonal velocity variable
    meridional_var: "timeDaily_avg_velocityMeridional"     # Name of meridional velocity variable  
    loss_type: "angular"    # Options: "angular", "cosine", "magnitude_weighted"
    eps: 1.0e-8
  denormalize_primary: false
  denormalize_direction: false  # Usually false since direction is scale-invariant

# Advanced configuration with multiple loss components
loss_function_advanced:
  _target_: src.losses.soma_losses.make_soma_composite_loss
  base_loss_name: "mse"
  enable_direction_loss: true
  direction_weight: 0.1
  direction_loss_config:
    zonal_var: "timeDaily_avg_velocityZonal"
    meridional_var: "timeDaily_avg_velocityMeridional"
    loss_type: "magnitude_weighted"  # Weights by velocity magnitude
  denormalize_primary: false
  denormalize_direction: false
  additional_losses:
    gradient_penalty:
      loss: 
        _target_: src.losses.custom_losses.GradientPenaltyLoss  # Example additional loss
      weight: 0.05
      denormalize: false

# Direct instantiation example (for programmatic use)
loss_function_direct:
  _target_: src.losses.soma_losses.SOMACompositeLoss
  primary_loss:
    _target_: torch.nn.MSELoss
    reduction: mean
  direction_loss:
    _target_: src.losses.soma_losses.DirectionLoss
    zonal_var: "timeDaily_avg_velocityZonal"
    meridional_var: "timeDaily_avg_velocityMeridional"
    loss_type: "cosine"
  direction_weight: 0.15
  denormalize_primary: false
  denormalize_direction: false

# For multi-variable scenarios
loss_function_multivariable:
  _target_: src.losses.soma_losses.SOMAMultiVariableLoss
  base_loss_fn:
    _target_: torch.nn.MSELoss
    reduction: mean
  variable_weights:
    u: 1.0
    v: 1.0
    temp: 0.8
    salt: 0.6
